### ISSUE TITLE
Unable to start dev build

### ISSUE THREAD

**Issue by olsharpe** [aragon/website#40]
When trying to run **npm start** I get the following error.

```
~/repo/aragon/website » npm start                                                                                                                      master ✗

> aragon-website@1.0.0 start /Users/***/Repo/aragon/website
> NODE_PRESERVE_SYMLINKS=1 react-static start

/Users/***/Repo/aragon/website/node_modules/@aragon/ui/src/index.js:1
(function (exports, require, module, __filename, __dirname) { export { default as theme, themeDark, brand, colors } from './theme'
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Module._extensions..js (module.js:671:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/***/Repo/aragon/website/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/***/Repo/aragon/website/static.config.js:5:1)
    at Module._compile (module.js:660:30)
    at loader (/Users/***/Repo/aragon/website/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/***/Repo/aragon/website/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:573:32)
```
Using the following Node & NPM versions

```
» node -v                                                                                                                        master ✗
v9.4.0
» npm -v                                                                                                                         master ✗
5.6.0
```

**Comment by bpierre** [comment]
@olsharpe 

You need to use the `website-stable` branch of Aragon UI to build the website, for now.

1/ Clone Aragon UI, checkout the branch, and `npm link` it:

```sh
$ git clone https://github.com/aragon/aragon-ui.git
$ cd aragon-ui
$ git checkout website-stable
$ npm link
```

2/ `npm link` Aragon UI from the website directory:

```sh
$ cd ~/website
$ npm link '@aragon/ui'
$ npm start
``

Tell me if that works for you!

**Comment by olsharpe** [comment]
@bpierre That has done the trick. Thank you
